/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentals;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import static movierentals.ConnectionGUI.db_name_txt;
import static movierentals.ConnectionGUI.port_num_txt;
import static movierentals.ConnectionGUI.serv_name_txt;
import static movierentals.ConnectionGUI.wb_pass_txt;
import static movierentals.RegisterGUI.regButton;

/**
 *
 * @author Adi
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form MovieRentalsGUI
     */
    public LoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userField = new java.awt.TextField();
        passField = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        loginButton = new java.awt.Button();
        registerButton = new java.awt.Button();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setText("Username");

        label2.setText("Password");

        loginButton.setLabel("Login");
        loginButton.setName(""); // NOI18N

        registerButton.setLabel("Register");

        label3.setText("Don't have an account?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        userField.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private static java.awt.Button loginButton;
    private static java.awt.TextField passField;
    private static java.awt.Button registerButton;
    private static java.awt.TextField userField;
    // End of variables declaration//GEN-END:variables

    public static void main() {
        LoginGUI LogGui = new LoginGUI();


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogGui.setVisible(true);
            }
        });

        loginButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (ConnectionGUI.getUser().login(userField.getText(), passField.getText())) {
                    JFrame frame = new JFrame();
                    MainGUI mainGUI = new MainGUI();    //adding MainGUI jpanel to frame
                    frame.add(mainGUI);
                    frame.setVisible(true);
                    frame.setLocationRelativeTo(null);
                    frame.pack();
                    LogGui.setVisible(false);
                    LogGui.dispose();
                } else {
                    JFrame jfwrong = new JFrame();
                    JPanel jpwrong = new JPanel();
                    JLabel jlwrong = new JLabel("Wrong username or password");
                    jpwrong.add(jlwrong);
                    jfwrong.add(jpwrong);
                    jfwrong.setVisible(true);
                    jfwrong.setLocationRelativeTo(null);
                    jfwrong.pack();
                }
            }
        });

        registerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                RegisterGUI reg = new RegisterGUI();
                JFrame frame = new JFrame(); 
                frame.add(reg);                 //adding registerGUI jpanel to frame
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.pack();
                LogGui.setVisible(false);
                LogGui.dispose();
                regButton.addActionListener(new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        String username = reg.textField1.getText().trim();
                        String password = reg.textField6.getText().trim();
                        String confirmPassword = reg.textField2.getText().trim();
                        String email = reg.textField3.getText().trim();
                        String fName = reg.textField4.getText().trim();
                        String lName = reg.textField5.getText().trim();

                        String error = "No data entered";

                        if (username.equals("") || username.equals(error)) {
                            reg.textField1.setText(error);
                        } else if (password.equals("") || password.equals(error)) {
                            reg.textField6.setText(error);
                        } else if (confirmPassword.equals("") || confirmPassword.equals(error)) {
                            reg.textField2.setText(error);
                        } else if (email.equals("") || email.equals(error)) {
                            reg.textField3.setText(error);
                        } else if (fName.equals("") || fName.equals(error)) {
                            reg.textField4.setText(error);
                        } else if (lName.equals("") || lName.equals(error)) {
                            reg.textField5.setText(error);
                        } else {
                            System.out.println(password);
                            System.out.println(confirmPassword);
                            ConnectionGUI.getUser().register(username, password, confirmPassword, email, fName, lName);
                        }
                    }
                });
            }
        });
        
        Movie movie = new Movie();
        //System.out.println(movie.getMovieInfo(myDatabase, "Sinister"));

    }

}
